; generated by PrusaSlicer 2.9.1 on 2025-03-17 at 08:49:34 UTC

; 

; external perimeters extrusion width = 1.69mm
; perimeters extrusion width = 1.69mm
; infill extrusion width = 1.69mm
; solid infill extrusion width = 1.69mm
; top infill extrusion width = 1.50mm

G10 S200 P0 ; set temperature
;TYPE:Custom
G21 ; Metric values
G90 ; Absolute positioning
G28 ; Home all axis
G1 X0 Y0 Z15 F1800 ; Move up before extruding

G92 E0;
G10 S200 P0 ; set temperature
M116 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M109 S200
M82
M107
;LAYER_CHANGE
;Z:1.5
;HEIGHT:1.5
G1 E-2 F2400
G92 E0
G1 E.00001
G1 Z1.5 F1800
G92 E0
G1 X221.425 Y221.425
G1 Z0
G1 E2 F2400
;COLOR_CHANGE,T0,#2512EF
M600
;TYPE:Perimeter
;WIDTH:1.6875
G1 F1800
G1 X78.575 Y221.425 E123.65447
G1 X78.575 Y78.575 E245.30894
G1 X221.425 Y78.575 E366.96341
G1 X221.425 Y150 E427.79064
G1 X221.425 Y221.2 E488.42626
G1 E486.42626 F2400
G92 E0
G1 X222.791 Y222.791 F1800
G1 E2 F2400
G1 F1800
G1 X77.209 Y222.791 E125.9811
G1 X77.209 Y77.209 E249.9622
G1 X222.791 Y77.209 E373.9433
G1 X222.791 Y150 E435.93385
G1 X222.791 Y222.566 E497.73279
G1 E495.73279 F2400
G92 E0
G1 X224.156 Y224.156 F1800
G1 E2 F2400
;TYPE:External perimeter
G1 F1800
G1 X75.844 Y224.156 E128.30604
G1 X75.844 Y75.844 E254.61208
G1 X224.156 Y75.844 E380.91812
G1 X224.156 Y150 E444.07114
G1 X224.156 Y223.931 E507.03254
G1 X222.673 Y224.154
G1 E505.03254 F2400
G92 E0
G1 X218.25 Y78.985 F1800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:1.68962
G1 F1800
G1 X220.401 Y81.135 E4.59404
G1 X220.401 Y83.069 E6.24364
G1 X216.931 Y79.599 E10.42933
G1 X214.997 Y79.599 E12.07893
G1 X220.401 Y85.003 E18.59751
G1 X220.401 Y86.938 E20.24796
G1 X213.062 Y79.599 E29.10063
G1 X211.128 Y79.599 E30.75023
G1 X220.401 Y88.872 E41.93579
G1 X220.401 Y90.806 E43.58539
G1 X209.194 Y79.599 E57.10384
G1 X207.26 Y79.599 E58.75344
G1 X220.401 Y92.74 E74.60478
G1 X220.401 Y94.675 E76.25523
G1 X205.325 Y79.599 E94.44066
G1 X203.391 Y79.599 E96.09026
G1 X220.401 Y96.609 E116.60858
G1 X220.401 Y98.543 E118.25818
G1 X201.457 Y79.599 E141.10939
G1 X199.523 Y79.599 E142.75899
G1 X220.401 Y100.477 E167.94309
G1 X220.401 Y102.412 E169.59354
G1 X197.588 Y79.599 E197.11173
G1 X195.654 Y79.599 E198.76133
G1 X220.401 Y104.346 E228.61241
G1 X220.401 Y106.28 E230.26201
G1 X193.72 Y79.599 E262.44598
G1 X191.786 Y79.599 E264.09558
G1 X220.401 Y108.214 E298.61243
G1 X220.401 Y110.149 E300.26288
G1 X189.851 Y79.599 E337.11383
G1 X187.917 Y79.599 E338.76343
G1 X220.401 Y112.083 E377.94727
G1 X220.401 Y114.017 E379.59687
G1 X185.983 Y79.599 E421.1136
G1 X184.049 Y79.599 E422.7632
G1 X220.401 Y115.951 E466.61281
G1 X220.401 Y117.886 E468.26326
G1 X182.114 Y79.599 E514.44697
G1 X180.18 Y79.599 E516.09657
G1 X220.401 Y119.82 E564.61317
G1 X220.401 Y121.754 E566.26277
G1 X178.246 Y79.599 E617.11226
G1 X176.312 Y79.599 E618.76186
G1 X220.401 Y123.688 E671.94423
G1 X220.401 Y125.623 E673.59468
G1 X174.377 Y79.599 E729.11115
G1 X172.443 Y79.599 E730.76075
G1 X220.401 Y127.557 E788.61011
G1 X220.401 Y129.491 E790.25971
G1 X170.509 Y79.599 E850.44195
G1 X168.575 Y79.599 E852.09155
G1 X220.401 Y131.425 E914.60668
G1 X220.401 Y133.36 E916.25713
G1 X166.64 Y79.599 E981.10636
G1 X164.706 Y79.599 E982.75596
G1 X220.401 Y135.294 E1049.93808
G1 X220.401 Y137.228 E1051.58768
G1 X162.772 Y79.599 E1121.10268
G1 X160.838 Y79.599 E1122.75228
G1 X220.401 Y139.162 E1194.60017
G1 X220.401 Y141.097 E1196.25062
G1 X158.903 Y79.599 E1270.43261
G1 X156.969 Y79.599 E1272.08221
G1 X220.401 Y143.031 E1348.59708
G1 X220.401 Y144.965 E1350.24668
G1 X155.035 Y79.599 E1429.09444
G1 X153.101 Y79.599 E1430.74404
G1 X220.401 Y146.899 E1511.92469
G1 X220.401 Y148.834 E1513.57514
G1 X151.166 Y79.599 E1597.08989
G1 X149.232 Y79.599 E1598.73949
G1 X220.401 Y150.768 E1684.58712
G1 X220.401 Y152.702 E1686.23672
G1 X147.298 Y79.599 E1774.41724
G1 X145.364 Y79.599 E1776.06684
G1 X220.401 Y154.636 E1866.58025
G1 X220.401 Y156.571 E1868.2307
G1 X143.429 Y79.599 E1961.0782
G1 X141.495 Y79.599 E1962.7278
G1 X220.401 Y158.505 E2057.90819
G1 X220.401 Y160.439 E2059.55779
G1 X139.561 Y79.599 E2157.07107
G1 X137.627 Y79.599 E2158.72067
G1 X220.401 Y162.373 E2258.56684
G1 X220.401 Y164.308 E2260.21729
G1 X135.692 Y79.599 E2362.39755
G1 X133.758 Y79.599 E2364.04715
G1 X220.401 Y166.242 E2468.5603
G1 X220.401 Y168.176 E2470.2099
G1 X131.824 Y79.599 E2577.05594
G1 X129.89 Y79.599 E2578.70554
G1 X220.401 Y170.11 E2687.88447
G1 X220.401 Y172.045 E2689.53492
G1 X127.955 Y79.599 E2801.04794
G1 X126.021 Y79.599 E2802.69754
G1 X220.401 Y173.979 E2916.54345
G1 X220.401 Y175.913 E2918.19305
G1 X124.087 Y79.599 E3034.37185
G1 X122.153 Y79.599 E3036.02145
G1 X220.401 Y177.847 E3154.53314
G1 X220.401 Y179.782 E3156.18359
G1 X120.218 Y79.599 E3277.02937
G1 X118.284 Y79.599 E3278.67897
G1 X220.401 Y181.716 E3401.85764
G1 X220.401 Y183.65 E3403.50724
G1 X116.35 Y79.599 E3529.0188
G1 X114.416 Y79.599 E3530.6684
G1 X220.401 Y185.584 E3658.51285
G1 X220.401 Y187.519 E3660.1633
G1 X112.481 Y79.599 E3790.34184
G1 X110.547 Y79.599 E3791.99144
G1 X220.401 Y189.453 E3924.50287
G1 X220.401 Y191.387 E3926.15247
G1 X108.613 Y79.599 E4060.99679
G1 X106.679 Y79.599 E4062.64639
G1 X220.401 Y193.321 E4199.8236
G1 X220.401 Y195.256 E4201.47405
G1 X104.744 Y79.599 E4340.98535
G1 X102.81 Y79.599 E4342.63495
G1 X220.401 Y197.19 E4484.47914
G1 X220.401 Y199.124 E4486.12874
G1 X100.876 Y79.599 E4630.30582
G1 X98.942 Y79.599 E4631.95542
G1 X220.401 Y201.058 E4778.46539
G1 X220.401 Y202.993 E4780.11584
G1 X97.007 Y79.599 E4928.9599
G1 X95.073 Y79.599 E4930.6095
G1 X220.401 Y204.927 E5081.78645
G1 X220.401 Y206.861 E5083.43605
G1 X93.139 Y79.599 E5236.94589
G1 X91.205 Y79.599 E5238.59549
G1 X220.401 Y208.795 E5394.43821
G1 X220.401 Y210.73 E5396.08866
G1 X89.27 Y79.599 E5554.26548
G1 X87.336 Y79.599 E5555.91508
G1 X220.401 Y212.664 E5716.42479
G1 X220.401 Y214.598 E5718.07439
G1 X85.402 Y79.599 E5880.91699
G1 X83.468 Y79.599 E5882.56659
G1 X220.401 Y216.532 E6047.74207
G1 X220.401 Y218.467 E6049.39252
G1 X81.533 Y79.599 E6216.9021
G1 X79.599 Y79.599 E6218.5517
G1 X220.401 Y220.401 E6388.39417
G1 X218.467 Y220.401 E6390.04377
G1 X79.599 Y81.533 E6557.55335
G1 X79.599 Y83.468 E6559.2038
G1 X216.532 Y220.401 E6724.37928
G1 X214.598 Y220.401 E6726.02888
G1 X79.599 Y85.402 E6888.87148
G1 X79.599 Y87.336 E6890.52108
G1 X212.664 Y220.401 E7051.03079
G1 X210.73 Y220.401 E7052.68039
G1 X79.599 Y89.27 E7210.85721
G1 X79.599 Y91.205 E7212.50766
G1 X208.795 Y220.401 E7368.35038
G1 X206.861 Y220.401 E7369.99998
G1 X79.599 Y93.139 E7523.50982
G1 X79.599 Y95.073 E7525.15942
G1 X204.927 Y220.401 E7676.33637
G1 X202.993 Y220.401 E7677.98597
G1 X79.599 Y97.007 E7826.83003
G1 X79.599 Y98.942 E7828.48048
G1 X201.058 Y220.401 E7974.99045
G1 X199.124 Y220.401 E7976.64005
G1 X79.599 Y100.876 E8120.81713
G1 X79.599 Y102.81 E8122.46673
G1 X197.19 Y220.401 E8264.31092
G1 X195.256 Y220.401 E8265.96052
G1 X79.599 Y104.744 E8405.47182
G1 X79.599 Y106.679 E8407.12227
G1 X193.321 Y220.401 E8544.29948
G1 X191.387 Y220.401 E8545.94908
G1 X79.599 Y108.613 E8680.7934
G1 X79.599 Y110.547 E8682.443
G1 X189.453 Y220.401 E8814.95443
G1 X187.519 Y220.401 E8816.60403
G1 X79.599 Y112.481 E8946.78257
G1 X79.599 Y114.416 E8948.43302
G1 X185.584 Y220.401 E9076.27747
G1 X183.65 Y220.401 E9077.92707
G1 X79.599 Y116.35 E9203.43863
G1 X79.599 Y118.284 E9205.08823
G1 X181.716 Y220.401 E9328.2669
G1 X179.782 Y220.401 E9329.9165
G1 X79.599 Y120.218 E9450.76228
G1 X79.599 Y122.153 E9452.41273
G1 X177.847 Y220.401 E9570.92442
G1 X175.913 Y220.401 E9572.57402
G1 X79.599 Y124.087 E9688.75282
G1 X79.599 Y126.021 E9690.40242
G1 X173.979 Y220.401 E9804.24833
G1 X172.045 Y220.401 E9805.89793
G1 X79.599 Y127.955 E9917.41095
G1 X79.599 Y129.89 E9919.0614
G1 X170.11 Y220.401 E10028.24033
G1 X168.176 Y220.401 E10029.88993
G1 X79.599 Y131.824 E10136.73597
G1 X79.599 Y133.758 E10138.38557
G1 X166.242 Y220.401 E10242.89872
G1 X164.308 Y220.401 E10244.54832
G1 X79.599 Y135.692 E10346.72858
G1 X79.599 Y137.627 E10348.37903
G1 X162.373 Y220.401 E10448.2252
G1 X160.439 Y220.401 E10449.8748
G1 X79.599 Y139.561 E10547.38808
G1 X79.599 Y141.495 E10549.03768
G1 X158.505 Y220.401 E10644.21807
G1 X156.571 Y220.401 E10645.86767
G1 X79.599 Y143.429 E10738.71517
G1 X79.599 Y145.364 E10740.36562
G1 X154.636 Y220.401 E10830.87903
G1 X152.702 Y220.401 E10832.52863
G1 X79.599 Y147.298 E10920.70915
G1 X79.599 Y149.232 E10922.35875
G1 X150.768 Y220.401 E11008.20638
G1 X148.834 Y220.401 E11009.85598
G1 X79.599 Y151.166 E11093.37073
G1 X79.599 Y153.101 E11095.02118
G1 X146.899 Y220.401 E11176.20183
G1 X144.965 Y220.401 E11177.85143
G1 X79.599 Y155.035 E11256.69919
G1 X79.599 Y156.969 E11258.34879
G1 X143.031 Y220.401 E11334.86366
G1 X141.097 Y220.401 E11336.51326
G1 X79.599 Y158.903 E11410.69525
G1 X79.599 Y160.838 E11412.3457
G1 X139.162 Y220.401 E11484.19359
G1 X137.228 Y220.401 E11485.84319
G1 X79.599 Y162.772 E11555.35819
G1 X79.599 Y164.706 E11557.00779
G1 X135.294 Y220.401 E11624.18991
G1 X133.36 Y220.401 E11625.83951
G1 X79.599 Y166.64 E11690.68874
G1 X79.599 Y168.575 E11692.33919
G1 X131.425 Y220.401 E11754.85432
G1 X129.491 Y220.401 E11756.50392
G1 X79.599 Y170.509 E11816.68616
G1 X79.599 Y172.443 E11818.33576
G1 X127.557 Y220.401 E11876.18512
G1 X125.623 Y220.401 E11877.83472
G1 X79.599 Y174.377 E11933.35119
G1 X79.599 Y176.312 E11935.00164
G1 X123.688 Y220.401 E11988.18401
G1 X121.754 Y220.401 E11989.83361
G1 X79.599 Y178.246 E12040.6831
G1 X79.599 Y180.18 E12042.3327
G1 X119.82 Y220.401 E12090.8493
G1 X117.886 Y220.401 E12092.4989
G1 X79.599 Y182.114 E12138.68261
G1 X79.599 Y184.049 E12140.33306
G1 X115.951 Y220.401 E12184.18267
G1 X114.017 Y220.401 E12185.83227
G1 X79.599 Y185.983 E12227.349
G1 X79.599 Y187.917 E12228.9986
G1 X112.083 Y220.401 E12268.18244
G1 X110.149 Y220.401 E12269.83204
G1 X79.599 Y189.851 E12306.68299
G1 X79.599 Y191.786 E12308.33344
G1 X108.214 Y220.401 E12342.85029
G1 X106.28 Y220.401 E12344.49989
G1 X79.599 Y193.72 E12376.68386
G1 X79.599 Y195.654 E12378.33346
G1 X104.346 Y220.401 E12408.18454
G1 X102.412 Y220.401 E12409.83414
G1 X79.599 Y197.588 E12437.35233
G1 X79.599 Y199.523 E12439.00278
G1 X100.477 Y220.401 E12464.18688
G1 X98.543 Y220.401 E12465.83648
G1 X79.599 Y201.457 E12488.68769
G1 X79.599 Y203.391 E12490.33729
G1 X96.609 Y220.401 E12510.85561
G1 X94.675 Y220.401 E12512.50521
G1 X79.599 Y205.325 E12530.69064
G1 X79.599 Y207.26 E12532.34109
G1 X92.74 Y220.401 E12548.19243
G1 X90.806 Y220.401 E12549.84203
G1 X79.599 Y209.194 E12563.36048
G1 X79.599 Y211.128 E12565.01008
G1 X88.872 Y220.401 E12576.19564
G1 X86.938 Y220.401 E12577.84524
G1 X79.599 Y213.062 E12586.69791
G1 X79.599 Y214.997 E12588.34836
G1 X85.003 Y220.401 E12594.86694
G1 X83.069 Y220.401 E12596.51654
G1 X79.599 Y216.931 E12600.70223
G1 X79.599 Y218.865 E12602.35183
G1 X81.75 Y221.015 E12604.94587
G1 E12602.94587 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
M104 S0
M83
G1 E-1 F300
G1 E-5 F9000
M82
;END gcode for filament
M104 S0 ; turn off temperature
M84     ; disable motors
;End of Gcode
; objects_info = {"objects":[]}
; filament used [mm] = 14090.14
; filament used [cm3] = 33.89
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 14m 13s
; estimated first layer printing time (normal mode) = 14m 13s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 1
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 0
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \nM104 S0\nM83\nG1 E-1 F300\nG1 E-5 F9000\nM82\n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nM84     ; disable motors\n;End of Gcode
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = UR5_APLA
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; filament_wipe = nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_height = 1.5
; first_layer_infill_speed = 0
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 1.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 500
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 1.5
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 20
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = UR5_APLA
; printer_model = 
; printer_notes = 
; printer_settings_id = UR5_APLA
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\nM109 S200\nM82"
; start_gcode = G21 ; Metric values\nG90 ; Absolute positioning\nG28 ; Home all axis\nG1 X0 Y0 Z15 F1800 ; Move up before extruding\n\nG92 E0;
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 20
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
